Refactor OTIO frame range collection
ynput/ayon-core pull request #1060
Opened 2024-12-16 14:00 UTC by jakubjezek001

## Changelog Description

## Additional info
- Removed unused function import.
- Added detailed logging for data updates.
- Streamlined frame range calculations and handling.
- Introduced a new class for collecting source frame ranges.
- Improved readability by cleaning up code structure.

## Testing notes:
1. start with this step
2. follow this step

2024-12-17 09:17 UTC, iLLiCiTiT commented on client/ayon_core/plugins/publish/collect_otio_frame_ranges.py
> +        otio_clip = instance.data["otioClip"]
```suggestion
        otio_clip = instance.data.get("otioClip")
        if otio_clip is None:
            self.log.debug("Skipping collect OTIO frame range.")
            return

        # get basic variables

```

2024-12-17 09:17 UTC, iLLiCiTiT commented on client/ayon_core/plugins/publish/collect_otio_frame_ranges.py
> +        if not instance.data.get("otioClip"):
Can we get rid of `hosts` filtering with this change?

2024-12-17 09:26 UTC, robin-ynput reviewed
I gave it a try through Hiero and it all works perfectly.

My only concern would be implementation-wise, currently it does:
```
Collect OTIO Frame Ranges [resolve, hiero, flame, traypublisher]:
* frameStart
* frameEnd
* clipIn
* clipOut
* clipInH
* clipOutH
```
then
```
Collect OTIO Frame Ranges (with media range) [hiero, flame]:
* frameStart (same value)
* frameEnd
* clipIn (same value)
* clipOut (same value)
* clipInH (same value)
* clipOutH (same value)
* sourceStart
* sourceEnd
* sourceStartH
* sourceEndH
```

I feel like there is quite some code duplication but more importantly to keep a single source of truth, I'd rather prefer to have :
```
Collect OTIO Frame Ranges [resolve, hiero, flame, traypublisher]:
* frameStart
* frameEnd
* clipIn
* clipOut
* clipInH
* clipOutH
```
then
```
Collect Retimed and Source OTIO Frame Ranges [hiero, flame]:
* frameEnd (retimed)
* sourceStart
* sourceEnd
* sourceStartH
* sourceEndH
```

What do you think ?

2024-12-17 09:33 UTC, iLLiCiTiT commented
I would like to avoid hosts filtering completelly if possible, but that would probably require more changes....

2025-01-14 10:43 UTC, iLLiCiTiT commented on client/ayon_core/plugins/publish/collect_otio_frame_ranges.py
> +    hosts = ["hiero", "flame"]
Shouldn't we instead use different family from product types to filter instances to avoid `hosts` filtering?

2025-01-14 10:46 UTC, iLLiCiTiT commented on client/ayon_core/plugins/publish/collect_otio_frame_ranges.py
> +class CollectOtioRetimedRanges(pyblish.api.InstancePlugin):
There are plugins `CollectOtioFrameRanges`, `CollectOtioSourceRanges`, `CollectOtioRetimedRanges`, is there reason why it's 3 plugins instead of one? From what I see in the code, 1 plugin could be 1 method...

2025-01-22 14:01 UTC, jakubjezek001 commented on client/ayon_core/plugins/publish/collect_otio_frame_ranges.py
> +    hosts = ["hiero", "flame"]
Not sure this is part of the scope of this PR. Also not up to me to decide how the workflow is designed.

2025-01-22 14:01 UTC, jakubjezek001 commented on client/ayon_core/plugins/publish/collect_otio_frame_ranges.py
> +    hosts = ["hiero", "flame"]
I am assuming it would be better to create Issue with redesign suggestion.

2025-01-22 14:04 UTC, jakubjezek001 commented on client/ayon_core/plugins/publish/collect_otio_frame_ranges.py
> +class CollectOtioRetimedRanges(pyblish.api.InstancePlugin):
Only reason we are splitting it into different plugins is that we need to approach collection of some attributes in particular context, with host and families filtering.

2025-01-23 14:14 UTC, iLLiCiTiT commented on client/ayon_core/plugins/publish/collect_otio_frame_ranges.py
> +    raise RuntimeError("OpenTimelineIO is not installed.")
Just remove the try > except block, it is unnecessary to capture error just to reraise different error hiding real error message.

2025-01-23 14:14 UTC, iLLiCiTiT commented on client/ayon_core/plugins/publish/collect_otio_frame_ranges.py
> +    return True
```suggestion
    return True

```

2025-01-23 14:15 UTC, iLLiCiTiT commented on client/ayon_core/plugins/publish/collect_otio_frame_ranges.py
> +    hosts = ["hiero", "flame"]
We're adding more and more plugins making it more and more hard to achieve that. Plugins in ayon-core should not have any filters in `hosts`.

2025-01-23 14:19 UTC, iLLiCiTiT commented on client/ayon_core/plugins/publish/collect_otio_frame_ranges.py
> +class CollectOtioRetimedRanges(pyblish.api.InstancePlugin):
`CollectOtioSourceRanges` and `CollectOtioRetimedRanges` have exactly same filters. Hosts filtering overall is related to this comment https://github.com/ynput/ayon-core/pull/1060/files#r1927050138 .

2025-01-24 13:53 UTC, jakubjezek001 commented on client/ayon_core/plugins/publish/collect_otio_frame_ranges.py
> +class CollectOtioRetimedRanges(pyblish.api.InstancePlugin):
implemented in https://github.com/ynput/ayon-core/pull/1060/commits/971c4aef43b5dad3f74b8f8ff321ef66c2927381

2025-01-24 13:53 UTC, jakubjezek001 commented on client/ayon_core/plugins/publish/collect_otio_frame_ranges.py
> +    raise RuntimeError("OpenTimelineIO is not installed.")
implemented in [`971c4ae` (#1060)](https://github.com/ynput/ayon-core/pull/1060/commits/971c4aef43b5dad3f74b8f8ff321ef66c2927381)

2025-01-27 13:54 UTC, robin-ynput requested changes

2025-01-27 13:54 UTC, robin-ynput commented on client/ayon_core/plugins/publish/collect_otio_frame_ranges.py
>          }
Correct me if I'm wrong but I believe the logic to compute the source range is actually wrong:
* source range is assumed as relative to the available range which is no more the cases with our OTIO exporters (except legacy Hiero).
* frame rate difference between source (e.g. 23.976fps) and available range (e.g. 50fps) of the clip is not handled by these maths

I had a check with a Hiero export and confirmed computed values were off.
This made me wondering where are those values actually used and what are the exepcted numbers (embedded timecode, relative to start_frame for sequence, ...) ?

If we are just looking for source range as frame numbers based on the available range I'd suggest this instead.

```suggestion
        # Backward-compatibility for Hiero OTIO exporter.
        # NTSC compatibility might introduce floating rates, when these are
        # not exactly the same (23.976 vs 23.976024627685547)
        # this will cause precision issue in computation.
        # Currently round to 2 decimals for comparison,
        # but this should always rescale after that.
        rounded_av_rate = round(otio_available_range.start_time.rate, 2)
        rounded_src_rate = round(otio_src_range.start_time.rate, 2)
        if rounded_av_rate != rounded_src_rate:
            conformed_src_in = otio_src_range.start_time.rescaled_to(
                otio_available_range.start_time.rate
            )
            conformed_src_duration = otio_src_range.duration.rescaled_to(
                otio_available_range.duration.rate
            )
            conformed_source_range = otio.opentime.TimeRange(
                start_time=conformed_src_in,
                duration=conformed_src_duration
            )

        else:
            conformed_source_range = source_range

        source_start = conformed_source_range.start_time
        source_end = source_start + conformed_source_range.duration

        handle_start = otio.opentime.RationalTime(
            instance.data.get("handleStart", 0),
            source_start.rate
        )
        handle_end = otio.opentime.RationalTime(
            instance.data.get("handleEnd", 0),
            source_start.rate
        )

        source_start_h = source_start - handle_start
        source_end_h = source_end + handle_end

        data = {
            "sourceStart": source_start.to_frames(),
            "sourceEnd": source_end.to_frames() - 1,
            "sourceStartH": source_start_h.to_frames(),
            "sourceEndH": source_end_h.to_frames() - 1,
        }
```

2025-01-27 13:54 UTC, robin-ynput commented on client/ayon_core/plugins/publish/collect_otio_frame_ranges.py
> +        media_out = int(retimed_attributes["mediaOut"])
should we also update `sourceStart, sourceEnd, sourceStartH` and `sourceEndH` from the retimed values ?

2025-01-30 10:13 UTC, jakubjezek001 commented on client/ayon_core/plugins/publish/collect_otio_frame_ranges.py
> +        media_out = int(retimed_attributes["mediaOut"])
I am guessing that we have to.

2025-02-11 09:58 UTC, robin-ynput commented
@jakubjezek001 @iLLiCiTiT this one should be ready to review.
I have added some automated tests to validate the computations (sequence, video and retimed).

2025-02-11 16:40 UTC, robin-ynput approved these changes

2025-02-25 08:35 UTC, merged