Use AYON settings - Part 1
ynput/ayon-core pull request #20
Opened 2024-02-09 16:55 UTC by iLLiCiTiT

## Changelog Description
Reduce AYON settings conversion from `ayon_settings.py`. More PRs will come.

## Additional info
All places that use the settings are expecting new structure of the settings. In some cases (color values) were changed types in settings to match expected value.

Some conversions are "questionable" for future, but that is not a goal of this PR.

## Testing notes:
Create all packages, ayon-core and server addon. Upload them to AYON.
- [x] Applications can be launched.
- [x] Maya settings should be applied to plugins - ExtractPlayblast, ExtractThumbnail, Validations etc. Colors of loaders are propagated.
- [x] Blender extract playblast/thumbnail.
- [x] Max PointCloud extraction.
- [ ] Deadline settings are loaded.

2024-02-12 16:42 UTC, simonebarbieri commented
I'm getting this error when running the launcher:
```
!!! AYON crashed:
Traceback (most recent call last):
  File "C:\Dev\Ynput\ayon-launcher\start.py", line 827, in main_cli
    cli.main()
  File "C:\Dev\Ynput\ayon-core\client\ayon_core\cli.py", line 265, in main
    _set_global_environments()
  File "C:\Dev\Ynput\ayon-core\client\ayon_core\cli.py", line 209, in _set_global_environments
    general_env = get_general_environments()
  File "C:\Dev\Ynput\ayon-core\client\ayon_core\settings\lib.py", line 259, in get_general_environments
    return json.loads(settings["core"]["environments"])
KeyError: 'environments'
```

2024-02-12 22:10 UTC, iLLiCiTiT commented
> I'm getting this error when running the launcher:

Fixed. You have to recreate ayon-core package and upload to server.

2024-02-13 09:38 UTC, BigRoy commented on client/ayon_core/plugins/publish/extract_review.py
> +            dict[str, Any]: Containg all output definitions matching entered
```suggestion
            dict[str, Any]: Containing all output definitions matching entered
```

2024-02-13 09:53 UTC, iLLiCiTiT commented on client/ayon_core/hosts/photoshop/plugins/publish/collect_review.py
> +    label = "Collect Review Family"
```suggestion
    label = "Collect Review"
```

2024-02-13 10:24 UTC, simonebarbieri approved these changes
Blender works fine!

2024-02-13 11:07 UTC, moonyuet approved these changes
Looks good in Max

2024-02-13 11:08 UTC, BigRoy commented
@simonebarbieri @moonyuet you should be able to check of the checkboxes in the "Testing Notes" if you've in particular checked that particular step, like pointcloud extraction in max and playblast/thumbnail in Blender, etc.

2024-02-13 11:56 UTC, tokejepsen requested changes
Submitting render from Maya to Deadline gives me this:
```
Traceback (most recent call last):
  File "C:\Users\tokejepsen\AppData\Local\Ynput\AYON\dependency_packages\ayon_2310271602_windows.zip\dependencies\pyblish\plugin.py", line 527, in __explicit_process
    runner(*args)
  File "C:\Users\tokejepsen\ayon-core\client\ayon_core\hosts\maya\plugins\publish\validate_render_image_rule.py", line 29, in process
    self.get_default_render_image_folder(instance)
  File "C:\Users\tokejepsen\ayon-core\client\ayon_core\hosts\maya\plugins\publish\validate_render_image_rule.py", line 63, in get_default_render_image_folder
    return instance.context.data.get('project_settings')\
AttributeError: 'NoneType' object has no attribute 'get'
```
Although this seems unrelated to the settings?

2024-02-13 12:07 UTC, iLLiCiTiT commented
> Submitting render from Maya to Deadline gives me this:

Should be fixed.

2024-02-13 12:39 UTC, tokejepsen requested changes
Nearly got a submission:
```
Traceback (most recent call last):
  File "C:\Users\tokejepsen\AppData\Local\Ynput\AYON\dependency_packages\ayon_2310271602_windows.zip\dependencies\pyblish\plugin.py", line 527, in __explicit_process
    runner(*args)
  File "C:\Users\tokejepsen\ayon-core\client\ayon_core\modules\deadline\abstract_submit_deadline.py", line 456, in process
    self.plugin_info = self.get_plugin_info()
  File "C:\Users\tokejepsen\ayon-core\client\ayon_core\modules\deadline\plugins\publish\submit_maya_deadline.py", line 260, in get_plugin_info
    instance.context.data['project_settings']
KeyError: 'RenderSettings'
```

2024-02-13 14:37 UTC, tokejepsen commented
Maya settings works. Also done Maya Deadline submission and works as well.

2024-02-13 14:37 UTC, tokejepsen approved these changes

2024-02-13 15:35 UTC, merged