Blender: Implement USD Extractor and Loader
ynput/ayon-core pull request #212
Opened 2024-03-20 16:10 UTC by BigRoy

## Changelog Description

Implement simple USD extract and load for Blender

## Additional info

This does not contain logic yet to 'contribute' the USD data into another USD Asset layer. That will be a separate PR.

## Testing notes:

1. Extract USD geometry from Blender
2. Load USD to Blender
3. Load Alembic to Blender should still work
4. Updating loaded content should work

2024-04-04 03:58 UTC, moonyuet commented on client/ayon_core/hosts/blender/plugins/load/load_abc.py
should we rename this as `load_cache_model.py` as it no longer only supports alembic loader.

2024-04-04 13:32 UTC, BigRoy commented on client/ayon_core/hosts/blender/plugins/publish/extract_usd.py
> +                use_instancing=True
I'd leave that for a separate PR - if you're ok with that.

2024-04-04 13:36 UTC, moonyuet commented on client/ayon_core/hosts/blender/plugins/publish/extract_usd.py
> +                use_instancing=True
Sure things!

2024-04-05 07:41 UTC, moonyuet approved these changes
Tested successfully in Blender. I also tried the loader with both model and usd family to make sure there is no bug encountered during the load too.

2024-04-19 11:13 UTC, LiborBatek commented
@BigRoy just started to "investigate" this PR and as I pulled it I dont see any Blender Addon Extractors settings for USD. is that correct? thx

![image](https://github.com/ynput/ayon-core/assets/112623825/7e209aa2-eec0-4ea4-b4e6-cfb1d1f3f4b2)

I have built the addon package for blender addon (ver 0.1.8) or?

2024-04-19 12:11 UTC, BigRoy commented
> @BigRoy just started to "investigate" this PR and as I pulled it I dont see any Blender Addon Extractors settings for USD. is that correct? thx
> 
> ![image](https://private-user-images.githubusercontent.com/112623825/323936735-7e209aa2-eec0-4ea4-b4e6-cfb1d1f3f4b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1Mjg5NjIsIm5iZiI6MTcxMzUyODY2MiwicGF0aCI6Ii8xMTI2MjM4MjUvMzIzOTM2NzM1LTdlMjA5YWEyLWVlYzAtNGVhNC1iNGU2LWNmYjFkMWYzZjRiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQxMjExMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmYyNTQ3YWYyYzRhMjM4NGU3OTNmNjZiM2IxYTMwMDFhYTYxMGY4ODY2ZGMwYTU5ZTMyYmRkMWUzYmNkNGY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0ut0UDZBBLUkFrujWRZUZWkhqVZ3SDBJA4bJCPWtPbc)
> 
> I have built the addon package for blender addon (ver 0.1.8) or?

Correct - this does not expose any settings for these extractors? What settings would you expect? Just whatever `Extract FBX` also exposes?

2024-04-19 12:15 UTC, LiborBatek requested changes
The USD creator / extractor is available within ```Publish``` but even if not select anything it does ```Validate``` ok even being empty.

Another issue is when using ```Load``` that as ```Alembic``` and ```USD``` being on the same loader user cannot choose which ```representation``` should be loaded which is not ideal...as now user cant go with ```Alembic``` ?
![Screenshot 2024-04-19 141210](https://github.com/ynput/ayon-core/assets/112623825/b67a4075-393a-46a5-af5a-fdd1a6769a13)

Or am I missing something?

2024-04-19 12:17 UTC, LiborBatek commented
> > @BigRoy just started to "investigate" this PR and as I pulled it I dont see any Blender Addon Extractors settings for USD. is that correct? thx
> > ![image](https://private-user-images.githubusercontent.com/112623825/323936735-7e209aa2-eec0-4ea4-b4e6-cfb1d1f3f4b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1Mjg5NjIsIm5iZiI6MTcxMzUyODY2MiwicGF0aCI6Ii8xMTI2MjM4MjUvMzIzOTM2NzM1LTdlMjA5YWEyLWVlYzAtNGVhNC1iNGU2LWNmYjFkMWYzZjRiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQxMjExMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmYyNTQ3YWYyYzRhMjM4NGU3OTNmNjZiM2IxYTMwMDFhYTYxMGY4ODY2ZGMwYTU5ZTMyYmRkMWUzYmNkNGY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0ut0UDZBBLUkFrujWRZUZWkhqVZ3SDBJA4bJCPWtPbc)
> > I have built the addon package for blender addon (ver 0.1.8) or?
> 
> Correct - this does not expose any settings for these extractors? What settings would you expect? Just whatever `Extract FBX` also exposes?

Well to be able to ```Disable``` it for example :)

2024-05-03 18:43 UTC, BigRoy commented
@LiborBatek tweaked some bits - let me know if you still get confused. 
The `model` family can now also publish USD and will also do so by default - configurable in settings.

2024-05-23 10:17 UTC, BigRoy commented
Ready to merge?

2024-05-23 11:22 UTC, merged