Maya: add support for Maya 2025
ynput/ayon-core pull request #293
Opened 2024-03-27 16:26 UTC by antirotor

## Changelog Description
Adding support to Maya 2025

## Additional info
This is adding default values to settings, moving around `capture.py` to Maya addon (where it should be anyway) and fixing some Qt imports there.

> [!NOTE]
> Touching `pyproject.toml` is done just to calm codespell in pre-commit hook because of the TVPaint path.

## Testing notes:
- Run Maya 2025 and it should work
- Run Maya 2024 should work too
- Playblasting should work also

2024-03-27 16:38 UTC, BigRoy approved these changes
Nice. Looks good to me.

Didn't do a test run.

2024-03-28 12:52 UTC, m-u-r-p-h-y requested changes
the menu shows up correctly all tools seems to run ok just:

some playblasting issue

```
Traceback (most recent call last):
  File "C:\Users\murph\AppData\Local\Ynput\AYON\dependency_packages\ayon_2402141620_windows.zip\dependencies\pyblish\plugin.py", line 527, in __explicit_process
    runner(*args)
  File "c:\Users\murph\Documents\Ayon\REPO\ayon-core\client\ayon_core\hosts\maya\plugins\publish\extract_playblast.py", line 60, in process
    lib.render_capture_preset(preset)
  File "c:\Users\murph\Documents\Ayon\REPO\ayon-core\client\ayon_core\hosts\maya\api\lib.py", line 239, in render_capture_preset
    path = capture.capture(log=self.log, **preset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\murph\Documents\Ayon\REPO\ayon-core\client\ayon_core\hosts\maya\vendor\python\capture.py", line 169, in capture
    with _independent_panel(width=width + padding,
  File "C:\Program Files\Autodesk\Maya2025\Python\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "c:\Users\murph\Documents\Ayon\REPO\ayon-core\client\ayon_core\hosts\maya\vendor\python\capture.py", line 614, in _independent_panel
    screen_width, screen_height = _get_screen_size()
                                  ^^^^^^^^^^^^^^^^^^
  File "c:\Users\murph\Documents\Ayon\REPO\ayon-core\client\ayon_core\hosts\maya\vendor\python\capture.py", line 872, in _get_screen_size
    rect = QtWidgets.QDesktopWidget().screenGeometry(-1)
           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'qtpy.QtWidgets' has no attribute 'QDesktopWidget'
```

2024-03-28 13:16 UTC, BigRoy commented
> QDesktopWidget

[It has been removed in `Qt6`](https://doc.qt.io/qt-6/widgets-changes-qt6.html#qdesktopwidget-and-qapplication-desktop) and thus `capture.py` would need to be updated.

You will need to use `QScreen`. I believe we're doing that elsewhere already. For example getting the screen geometry [here](https://github.com/ynput/ayon-core/blob/a4f2f76fbf98becd22b75012abf1abfc09bbd69d/client/ayon_core/tools/publisher/widgets/screenshot_widget.py#L172-L173)

2024-04-02 11:59 UTC, antirotor commented on pyproject.toml
> +ignore-words-list = "ayon,ynput,developpement"
Sure, but codespell pre-commit hook will not allow to commit unless this is added to exceptions.

2024-04-02 13:10 UTC, m-u-r-p-h-y approved these changes
Maya 2025 publishing, including playblast creation works as expected

![image](https://github.com/ynput/ayon-core/assets/352795/7991cc59-eb3f-4503-b259-e8c96ac0ad62)

2024-04-10 10:05 UTC, merged