Maya: Set scene fps - apply playback options in one call
ynput/ayon-core pull request #323
Opened 2024-03-29 13:31 UTC by BigRoy

## Changelog Description

Don't set time slider values one by one, but set all at once.

## Additional info

Less maya calls is always good.

## Testing notes:

1. Updating scene fps should work. (e.g. reset frame range) or by the 'fix' in the prompt on scene save if your scene is wrong FPS.

2024-03-30 19:06 UTC, m-u-r-p-h-y requested changes
Should not we already take the values from the task, not the shot? It was true for OP but in Ayon we already have task level attributes.

Also can I ask for improving the info message we print to the script editor? We only inform about the fps change, it would be great to include all attributes we touch (frameStart, frameEnd)

![image](https://github.com/ynput/ayon-core/assets/352795/f45a8032-8aea-4c8e-afb9-bfda84c93a5f)

2024-04-01 11:24 UTC, MustafaJafar approved these changes
It works on my side.

2024-04-01 12:02 UTC, MustafaJafar commented
> Should not we already take the values from the task, not the shot? It was true for OP but in Ayon we already have task level attributes.

Yeah, I traced that and found the problem which is not related to this PR.
Going to make a PR for that.

2024-04-02 05:11 UTC, tokejepsen requested changes
Could you update the title and description as this only affects the time range and not the FPS?

2024-04-02 07:45 UTC, BigRoy commented
> Could you update the title and description as this only affects the time range and not the FPS?

Well spotted. Thanks!



> > Should not we already take the values from the task, not the shot? It was true for OP but in Ayon we already have task level attributes.
> 
> Yeah, I traced that and found the problem which is not related to this PR. I made a PR #338

Nice work and good thinking!

2024-04-04 07:07 UTC, tokejepsen approved these changes

2024-04-04 07:08 UTC, merged