Maya: Enhancement on reset frame range based on fps
ynput/ayon-core pull request #467
Opened 2024-04-30 05:47 UTC by moonyuet

## Changelog Description
- Support for fps options in terms of maya settings(such as 2, 3, 4, 5, 6, 8, 10, 12, 16 fps)
- Support to set fps value based on the task

## Additional info
n/a

## Testing notes:
1. Go to ayon server -> Project Setting -> project and select your project
2. Set the fps value based for your task
![image](https://github.com/ynput/ayon-core/assets/64118225/04debc48-9f16-4e94-890e-835a8ec0e99e)
3. Launch Maya
4. Access AYON menubar -> Set frame range
5. Should be set the fps value according to the project setting.

2024-04-30 07:37 UTC, tokejepsen requested changes
Tested successfully in Maya 2023. Just that small code cosmetics suggestion.

2024-04-30 07:37 UTC, tokejepsen commented on client/ayon_core/hosts/maya/api/lib.py
> +        # 2, 3, 4, 5, 6, 8, 10, 12, 16
```suggestion
```
Dont think this comment adds anything.

2024-04-30 08:16 UTC, tokejepsen approved these changes
Ready to merge.

2024-04-30 08:20 UTC, merged

2024-05-22 08:32 UTC, iLLiCiTiT commented on client/ayon_core/hosts/maya/api/lib.py
> +                fps = 25
A little bit late, but yes it is the case. There are more places that should be cleaned up over time, usually frame start/end and fps.